version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    # env_file:
    #   - .env
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    command: bash -c "celery -A hatch_messaging worker --loglevel=info"
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER}
      - CELERY_RESULT_BACKEND=${CELERY_BACKEND}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
    depends_on:
      - web
      - redis
volumes:
  postgres_data:
